### PR TITLE
Add CI to repo

### PR DESCRIPTION
**Pull request by laurenchilutti**
**Description**

Adding CI tests to this repo. This brings over a similar workflow as is done in the GFDL_atmos_cubed_sphere repository. Will build solo model (nh, sw, and hydro) and then run the 35 tests in RTS/CI.

Fixes # (issue)

**How Has This Been Tested?**

Tested by the successful checks on this PR

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by bensonr — APPROVED** [review]

**Review by lharris4 — COMMENTED** [review]
Hi, Lauren. Thanks for putting this together. Are these runs intended to test the full-physics SHiELD or just the solo_core?

**Comment by laurenchilutti** [comment]
This will only test the solo shield.  I could add in more tests to test build full shield configurations.  And I can look into how feasible it would be to run a full shield model on the cloud - main concerns would be getting the input data onto the cloud and how expensive storage of input data may be.

**Review by lharris4 — APPROVED** [review]

**Comment by lharris4** [comment]
Thank you for clarifying that. We would probably need some reduced
configurations to make it feasible to test SHiELD in the cloud if we want
to do that at all. Testing solo_core is good enough for now.

**Comment by lharris4** [comment]
I realize I never merged this. Let me take care of this.

**Pull request merged**
