### PR TITLE
Fix prescribed Q-flux bug and improve user experience of SOM

### LINKED ISSUE #34: Slab ocean Q-flux is read in from file, but not propagated to `Sfcprop%qfluxadj`
**Describe the bug**

Within `sfcsub.F`, infrastructure is in place to read in an ocean Q-flux from a file into a locally defined `qflux` variable in the `clima` subroutine: https://github.com/NOAA-GFDL/SHiELD_physics/blob/d44f50f2cf0fab2b7919df84da5a419c01d55164/gsmphys/sfcsub.F#L7521-L7533

However, data from this local `qflux` variable is not propagated to the output `qfluxadj` variable, and therefore the Q-flux assigned to `Sfcprop%qfluxadj` (for eventual use elsewhere in the model) is always zero.

**To Reproduce**

Run SHiELD with a prescribed Q-flux file, i.e. with a file specified for the `namsfc.fnqfluxc` namelist parameter.  It is useful to define a diagnostic pointing to `Sfcprop%qfluxadj` to assess this (I have done this in a fork).

**Expected behavior**

`qfluxadj` should be populated in a similar manner to `mldclm`, i.e. interpolated between monthly means loaded in from a file: https://github.com/NOAA-GFDL/SHiELD_physics/blob/d44f50f2cf0fab2b7919df84da5a419c01d55164/gsmphys/sfcsub.F#L8008-L8012

I have implemented this in a fork, and it seems to address this issue.  I will make a PR after a little more testing.

### PR DESCRIPTION
**Pull request by spencerkclark**
**Description** 

This PR fixes a bug in reading in a climatological Q-flux prescribed from a file, and adds a couple diagnostics to allow for easier inspection of the instantaneous values of the Q-flux and mixed layer depth prescribed.

Note I have included another minor change to the slab ocean model code, which removes the `iostat` argument from the namelist read call.  If `iostat` is included in this call and namelist parameters are mistyped, then the simulation will continue without reading the rest of the variables in the `ocean_nml` namelist, leading to difficult to debug / unexpected behavior.  With `iostat` removed—[as is done elsewhere in the code](https://github.com/NOAA-GFDL/SHiELD_physics/blob/d44f50f2cf0fab2b7919df84da5a419c01d55164/GFS_layer/GFS_typedefs.F90#L2528)—the model will immediately crash with an informative error message, making configuration typos less dangerous and easier to debug, e.g.:

```
At line 136 of file /SHiELD/SHiELD_SRC/SHiELD_physics/gsmphys/som_mlm.F90
Fortran runtime error: Cannot match namelist object name mld_restore_timescale
```

Fixes #34 

**How Has This Been Tested?**

I have tested this by running SHiELD with a Q-flux and mixed layer depth prescribed from files, and have plotted snapshots of the newly added diagnostics.  Results look as expected given the data I prescribed.

2023-12-13-prescribed-qflux

2023-12-13-prescribed-mld

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gaokun227 — APPROVED** [review]
Looks good to me

**Comment by spencerkclark** [comment]
Thanks @lharris4 and @gaokun227!  

If you don't mind, now that #36 and NOAA-GFDL/atmos_drivers#32 have been merged, I may convert the `MLDI` and `prescribed_qflux` diagnostics to diagnostics manager controlled fields.  It occurred to me we may want to have the option of outputting these as interval-average fields instead of instantaneous (diagnostics manager controlled fields can have this toggled through the diagnostics table).  Now that we pass `Sfcprop` to the `register_diag_manager_controlled_diagnostics` routine that should be straightforward.

**Comment by lharris4** [comment]
@spencerkclark do go ahead and move these to `diag_manager` controlled fields. I believe this is to allow the diagnostics manager to do the averaging and accumulation instead of relying on a 'bucket' as many of the physics driver diagnostics do?

**Comment by spencerkclark** [comment]
Thanks @lharris4!  

That's exactly right.  That was my motivation for adding that infrastructure originally.  Hopefully others find it useful to plug into as well, so long as I don't inadvertently break it as I did in #36 😬.  Fortunately this PR led me to catch / fix it quickly (see 682ada5).  I should add some diagnostics manager controlled fields to [my regression test configuration in the SHiELD-wrapper repo](https://github.com/ai2cm/SHiELD-wrapper/blob/main/wrapper/tests/pytest/config/default.yml), which would have caught this.

**Pull request merged**
