### PR TITLE
Add instantaneous snow fraction diagnostic

### PR DESCRIPTION
**Pull request by spencerkclark**
**Description**

This PR adds an instantaneous snow cover fraction diagnostic to SHiELD.  When plotting this field, one somewhat odd aspect that stood out is that the snow cover is non-zero over some ocean grid cells.  For the test run I did this was most noticeable in the North Pole tile.  This is illustrated in the figure below, which plots snapshots of the snow cover, snow depth, and snow water equivalent depth for the North Pole tile masked to only ocean grid cells.  The snow cover is non-zero at some points, but the snow depth and snow water equivalent depth are zero everywhere (which is more in line with what we would expect).

2024-06-04-snow-fraction-ocean-mask

**How Has This Been Tested?**

This has been tested by running a short C24 resolution simulation and plotting the result for the diagnostic and comparing it with other snow-related diagnostics like the snow depth and snow water equivalent depth.

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by bensonr** [comment]
@spencerkclark - this is still listed as a draft PR. Does it need to be changed?

**Comment by lharris4** [comment]
The non-zero snow-cover fraction is probably due to snow falling on open water and being recorded in the time-average before melting into the ocean.

**Comment by spencerkclark** [comment]
@bensonr sorry, yes, I marked it as a draft because I am concerned about the non-zero values over ocean.

@lharris4 sorry, I'm not sure I understand—where is the time average occurring?

**Comment by lharris4** [comment]
@spencerkclark sorry I may have misunderstood that the PR is both the addition of this instantaneous diagnostic and also a description of the issue in snow fraction with the new diagnostic. However I believe my description of why the non-zero snow fraction is happening is still valid.

**Comment by lharris4** [comment]
@kaiyuan-cheng Do you know precisely how the snow fraction is being computed in SHiELD, and why we would get non-zero instantaneous snow fraction over an area with zero snow depth?

**Comment by kaiyuan-cheng** [comment]
This is indeed strange. A non-zero snow fraction only occurs when there is a non-zero snow depth, e.g., the [calculation](https://github.com/NOAA-GFDL/SHiELD_physics/blob/5e5e100c068d55b8247dcb428f9df36fb31bdf35/gsmphys/module_sf_noahmplsm.f90#L1654) in Noah-MP. Let me take a closer look at it.

**Comment by kaiyuan-cheng** [comment]
It turns out that those non-zero snow fractions over the ocean originate from the surface restart files, likely as a result of the regridding process. They remain unchanged throughout the model integration as the LSM is never called for the ocean grids.

**Comment by kaiyuan-cheng** [comment]
I forgot to mention that there will be no snow fractions over the ocean for a cold-start run.

**Comment by spencerkclark** [comment]
Thanks @kaiyuan-cheng—indeed that's what I noticed too.  The restart files in the test case I sent you were from a case that I had originally started from GFS analysis initial conditions (i.e. a cold start, where the model must compute the snow cover from other variables).  I think what this must suggest is that the snow cover is left behind from sea-ice grid cells when they flip to ocean grid cells.  

Do you think there would be any harm in adding some simple logic to the physics driver that would set the snow cover fraction to zero at all ocean grid cells every timestep?

**Comment by kaiyuan-cheng** [comment]
@spencerkclark I think it will be fine to set the snow cover fraction to zero at all ocean grids every timestep. Or we set it to zero during the initialization.

**Comment by spencerkclark** [comment]
Sounds good @kaiyuan-cheng—I'll plan on making that change.  I think we need it every timestep to guarantee the diagnostic will not have non-zero values at ocean grid cells.

**Comment by kaiyuan-cheng** [comment]
@spencerkclark You are right. We should do it every timestep as the sea-land-mask would change when using external SST.

**Comment by spencerkclark** [comment]
In the case when we are prescribing the sea surface temperature and sea ice via data override we may also want to reset `Sfcprop%snowd` and `Sfcprop%weasd` to zero when a grid cell becomes ocean after being sea ice, since I think where this generally happens is in the surface cycling routine, which does not get called every timestep (I typically use a cycling frequency of one day).  I ran a simple a test and confirmed this was the case.

I went ahead and pushed this and the change to reset the snow cover fraction over ocean every timestep.  This plot shows that the added `snow_cover` diagnostic now has the expected behavior over ocean:

2024-06-07-snow-fraction-ocean-mask

Let me know if things look good.  Thanks!

**Comment by lharris4** [comment]
This change makes sense to me. Thank you for adding these.

**Review by lharris4 — APPROVED** [review]

**Comment by spencerkclark** [comment]
Thanks @lharris4 and @kaiyuan-cheng!  @bensonr this should be ready for review now.

**Review by bensonr — APPROVED** [review]

**Comment by spencerkclark** [comment]
Thanks @bensonr and @laurenchilutti!

**Pull request merged**
