### PR TITLE
fix bug when calling unallocated diagnostics

### PR DESCRIPTION
**Pull request by JosephMouallem**
**Description**

The subroutine `compute_column_integrated_moles_of_dry_air_and_co2` is [called](https://github.com/NOAA-GFDL/SHiELD_physics/blob/main/GFS_layer/GFS_radiation_driver.F90#L1389) by default to compute:
`Diag%column_moles_dry_air_per_square_meter` and `Diag%column_moles_co2_per_square_meter` in [GFS_layer/GFS_radiation_driver.F90:](https://github.com/NOAA-GFDL/SHiELD_physics/blob/main/GFS_layer/GFS_radiation_driver.F90#L1946)

These quantities are not allocated in [GFS_layer/GFS_typedefs.F90](https://github.com/NOAA-GFDL/SHiELD_physics/blob/main/GFS_layer/GFS_typedefs.F90#L3923) if ldiag3d is false in gfs_physics_nml.
Thus, this causes a code crash.
This PR will add an if statement before calling compute_column_integrated_moles_of_dry_air_and_co2

Tested within shield in debug mode with the current public release branches.

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x]  My changes generate no new warnings
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by spencerkclark — COMMENTED** [review]
Oops sorry @JosephMouallem this was my bad...how do you feel about flipping this (i.e. always allocating these fields in `GFS_typedefs.F90`) such that one does not need to set `ldiag3d = .true.` to use the `global_mean_co2` diagnostic?

I changed my mind midway through implementing it in #45, and apparently neglected to test it with `ldiag3d = .false.`, leaving it in this semi-broken state.

**Comment by spencerkclark** [comment]
Thanks @lharris4—I agree.  Sorry for not making my reasoning clearer.

**Comment by JosephMouallem** [comment]
Thanks @spencerkclark @lharris4 for sharing you thoughts. I moved these fields out of ldiag3d.
@spencerkclark no worries. Please let know if you would like to make any other changes.

**Review by spencerkclark — APPROVED** [review]
Thanks @JosephMouallem—this looks good to me now!

**Review by linjiongzhou — APPROVED** [review]
Hi Joseph and Spencer,

Thanks for your effort on this. It looks good to me.

Linjiong

**Comment by spencerkclark** [comment]
A gentle ping on this, which I think should be a quick merge.

**Comment by lharris4** [comment]
@spencerkclark sorry for the delay. I have completed the merge.

**Comment by spencerkclark** [comment]
All good, just wanted to make sure it didn't get lost.  Thanks!

**Pull request merged**
